In [1]:
from google.colab import files
uploaded = files.upload()

Saving archive (1).zip to archive (1).zip

In [2]:
import zipfile
import os

zip_path = "archive (1).zip"  # Replace with actual filename
extract_path = "/content/dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")

Dataset extracted successfully!

In [3]:
os.listdir("/content/dataset")

['fertilizer_recommendation.csv']

In [6]:
import pandas as pd

df = pd.read_csv("/content/dataset/fertilizer_recommendation.csv")
df.head()

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Nitrogen_Level,Phosphorus_Level,Potassium_Level,Temperature,Humidity,Rainfall,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Previous_Crop,Region,Fertilizer_Used_Last_Season,Yield_Last_Season,Recommended_Fertilizer
0,Clay,6.07,34.98,0.32,1.87,61,44,84,19.84,83.31,1693.22,Cotton,Harvest,Kharif,Canal,Wheat,South,297.15,1.19,MOP
1,Silt,6.39,47.34,0.28,0.21,59,56,18,24.40,46.27,1030.21,Maize,Vegetative,Kharif,Sprinkler,Potato,Central,77.17,4.40,Urea
2,Sandy,7.92,38.13,0.99,1.88,43,21,119,24.82,71.86,1166.16,Cotton,Flowering,Kharif,Rainfed,Tomato,South,128.93,7.21,Urea
3,Clay,5.86,14.17,1.46,0.36,88,46,34,27.87,53.23,2881.83,Wheat,Flowering,Zaid,Sprinkler,Potato,West,233.96,1.85,MOP
4,Clay,7.98,19.28,0.85,2.16,104,53,98,24.17,51.87,714.84,Potato,Sowing,Kharif,Rainfed,Maize,East,214.39,7.36,Zinc Sulphate

In [7]:
!pip install lightgbm optuna

Requirement already satisfied: lightgbm in /usr/local/lib/python3.12/dist-packages (4.6.0)
Collecting optuna
  Downloading optuna-4.7.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from lightgbm) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from lightgbm) (1.16.3)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.3)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.46)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.7.0-py3-none-any.whl (413 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.9/413.9 kB 28.1 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.7.0

In [8]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

import lightgbm as lgb
import optuna

In [9]:
df = pd.read_csv("/content/dataset/fertilizer_recommendation.csv")
df.head()

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Nitrogen_Level,Phosphorus_Level,Potassium_Level,Temperature,Humidity,Rainfall,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Previous_Crop,Region,Fertilizer_Used_Last_Season,Yield_Last_Season,Recommended_Fertilizer
0,Clay,6.07,34.98,0.32,1.87,61,44,84,19.84,83.31,1693.22,Cotton,Harvest,Kharif,Canal,Wheat,South,297.15,1.19,MOP
1,Silt,6.39,47.34,0.28,0.21,59,56,18,24.40,46.27,1030.21,Maize,Vegetative,Kharif,Sprinkler,Potato,Central,77.17,4.40,Urea
2,Sandy,7.92,38.13,0.99,1.88,43,21,119,24.82,71.86,1166.16,Cotton,Flowering,Kharif,Rainfed,Tomato,South,128.93,7.21,Urea
3,Clay,5.86,14.17,1.46,0.36,88,46,34,27.87,53.23,2881.83,Wheat,Flowering,Zaid,Sprinkler,Potato,West,233.96,1.85,MOP
4,Clay,7.98,19.28,0.85,2.16,104,53,98,24.17,51.87,714.84,Potato,Sowing,Kharif,Rainfed,Maize,East,214.39,7.36,Zinc Sulphate

In [10]:
TARGET = "Recommended_Fertilizer"

In [11]:
DROP_COLS = [
    "Yield_Last_Season",
    "Fertilizer_Used_Last_Season"
]

df = df.drop(columns=DROP_COLS, errors="ignore")

In [12]:
categorical_features = [
    "Soil_Type",
    "Crop_Type",
    "Crop_Growth_Stage",
    "Season",
    "Irrigation_Type",
    "Previous_Crop",
    "Region"
]

numerical_features = [
    "Soil_pH",
    "Soil_Moisture",
    "Organic_Carbon",
    "Electrical_Conductivity",
    "Nitrogen_Level",
    "Phosphorus_Level",
    "Potassium_Level",
    "Temperature",
    "Humidity",
    "Rainfall"
]

In [13]:
# Numerical → median
for col in numerical_features:
    df[col] = df[col].fillna(df[col].median())

# Categorical → mode
for col in categorical_features:
    df[col] = df[col].fillna(df[col].mode()[0])

In [14]:
label_encoders = {}

for col in categorical_features:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [15]:
df["NPK_Ratio"] = (
    df["Nitrogen_Level"] +
    df["Phosphorus_Level"] +
    df["Potassium_Level"]
) / 3

In [16]:
df["Moisture_Rain_Interaction"] = df["Soil_Moisture"] * df["Rainfall"]

In [17]:
df["Climate_Stress"] = df["Temperature"] / (df["Humidity"] + 1)

In [22]:
from sklearn.preprocessing import LabelEncoder

target_encoder = LabelEncoder()
df[TARGET] = target_encoder.fit_transform(df[TARGET])

df[TARGET].head()

0    2
1    5
2    5
3    2
4    6
Name: Recommended_Fertilizer, dtype: int64

In [23]:
X = df.drop(columns=[TARGET])
y = df[TARGET]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [30]:
def objective(trial):

    params = {
        "objective": "multiclass",
        "num_class": y.nunique(),
        "metric": "multi_logloss",
        "boosting_type": "gbdt",
        "verbosity": -1,

        # 🔥 REQUIRED FOR OPTUNA + min_data_in_leaf
        "feature_pre_filter": False,

        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.15),
        "num_leaves": trial.suggest_int("num_leaves", 20, 300),
        "max_depth": trial.suggest_int("max_depth", 3, 12),
        "min_data_in_leaf": trial.suggest_int("min_data_in_leaf", 10, 100),
        "feature_fraction": trial.suggest_float("feature_fraction", 0.6, 1.0),
        "bagging_fraction": trial.suggest_float("bagging_fraction", 0.6, 1.0),
        "bagging_freq": trial.suggest_int("bagging_freq", 1, 7),
        "lambda_l1": trial.suggest_float("lambda_l1", 0.0, 5.0),
        "lambda_l2": trial.suggest_float("lambda_l2", 0.0, 5.0)
    }

    # 🔥 CREATE DATASET INSIDE OBJECTIVE
    train_data = lgb.Dataset(X_train, label=y_train)
    valid_data = lgb.Dataset(X_test, label=y_test)

    model = lgb.train(
        params,
        train_data,
        valid_sets=[valid_data],
        num_boost_round=300,
        callbacks=[lgb.early_stopping(30, verbose=False)]
    )

    preds = model.predict(X_test)
    preds = np.argmax(preds, axis=1)

    return accuracy_score(y_test, preds)

In [31]:
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=50)

study.best_value, study.best_params

[I 2026-02-16 17:14:34,236] A new study created in memory with name: no-name-6ba244c7-14ff-4740-b3cb-ea3aee89e1b3
[I 2026-02-16 17:14:35,388] Trial 0 finished with value: 0.875 and parameters: {'learning_rate': 0.14643270644639444, 'num_leaves': 197, 'max_depth': 9, 'min_data_in_leaf': 11, 'feature_fraction': 0.9311312451023719, 'bagging_fraction': 0.6932082601891683, 'bagging_freq': 6, 'lambda_l1': 2.9789049452766267, 'lambda_l2': 2.996319993016871}. Best is trial 0 with value: 0.875.
[I 2026-02-16 17:14:37,467] Trial 1 finished with value: 0.873 and parameters: {'learning_rate': 0.08303389566167103, 'num_leaves': 225, 'max_depth': 10, 'min_data_in_leaf': 11, 'feature_fraction': 0.6663171895525756, 'bagging_fraction': 0.9856274068295166, 'bagging_freq': 2, 'lambda_l1': 0.3024909985106683, 'lambda_l2': 0.6155396724779555}. Best is trial 0 with value: 0.875.
[I 2026-02-16 17:14:38,142] Trial 2 finished with value: 0.8735 and parameters: {'learning_rate': 0.1464807607755581, 'num_leaves': 215, 'max_depth': 5, 'min_data_in_leaf': 39, 'feature_fraction': 0.755731225621944, 'bagging_fraction': 0.8002405511255722, 'bagging_freq': 1, 'lambda_l1': 4.81767153388237, 'lambda_l2': 2.7229344556634376}. Best is trial 0 with value: 0.875.
[I 2026-02-16 17:14:39,008] Trial 3 finished with value: 0.8775 and parameters: {'learning_rate': 0.1326812025928069, 'num_leaves': 153, 'max_depth': 11, 'min_data_in_leaf': 58, 'feature_fraction': 0.6639499135437816, 'bagging_fraction': 0.9661505476150403, 'bagging_freq': 1, 'lambda_l1': 4.159695763419765, 'lambda_l2': 2.486144155312091}. Best is trial 3 with value: 0.8775.
[I 2026-02-16 17:14:40,170] Trial 4 finished with value: 0.871 and parameters: {'learning_rate': 0.0979052920242565, 'num_leaves': 85, 'max_depth': 11, 'min_data_in_leaf': 63, 'feature_fraction': 0.8312100932344548, 'bagging_fraction': 0.7108133550263395, 'bagging_freq': 1, 'lambda_l1': 1.4755121406023348, 'lambda_l2': 2.0939013260346204}. Best is trial 3 with value: 0.8775.
[I 2026-02-16 17:14:40,813] Trial 5 finished with value: 0.8745 and parameters: {'learning_rate': 0.1343024032464885, 'num_leaves': 135, 'max_depth': 3, 'min_data_in_leaf': 77, 'feature_fraction': 0.6696757792203137, 'bagging_fraction': 0.8812302138439085, 'bagging_freq': 1, 'lambda_l1': 3.402835682969574, 'lambda_l2': 3.2829862173406656}. Best is trial 3 with value: 0.8775.
[I 2026-02-16 17:14:45,977] Trial 6 finished with value: 0.8735 and parameters: {'learning_rate': 0.020798868562916364, 'num_leaves': 233, 'max_depth': 4, 'min_data_in_leaf': 80, 'feature_fraction': 0.8922806406450557, 'bagging_fraction': 0.9532021570493457, 'bagging_freq': 7, 'lambda_l1': 0.6905023644006342, 'lambda_l2': 4.7128254286337885}. Best is trial 3 with value: 0.8775.
[I 2026-02-16 17:14:49,031] Trial 7 finished with value: 0.8755 and parameters: {'learning_rate': 0.02455114548380564, 'num_leaves': 63, 'max_depth': 12, 'min_data_in_leaf': 88, 'feature_fraction': 0.9547790180552338, 'bagging_fraction': 0.6151352299481482, 'bagging_freq': 5, 'lambda_l1': 3.1057120496131096, 'lambda_l2': 2.7328752472080757}. Best is trial 3 with value: 0.8775.
[I 2026-02-16 17:14:50,609] Trial 8 finished with value: 0.8725 and parameters: {'learning_rate': 0.08772497980930125, 'num_leaves': 108, 'max_depth': 10, 'min_data_in_leaf': 34, 'feature_fraction': 0.7247632947794163, 'bagging_fraction': 0.9447537111839844, 'bagging_freq': 6, 'lambda_l1': 1.566558293645084, 'lambda_l2': 0.5454066961018572}. Best is trial 3 with value: 0.8775.
[I 2026-02-16 17:14:51,325] Trial 9 finished with value: 0.875 and parameters: {'learning_rate': 0.1400896401549379, 'num_leaves': 228, 'max_depth': 4, 'min_data_in_leaf': 64, 'feature_fraction': 0.9165667559286561, 'bagging_fraction': 0.8598494186726685, 'bagging_freq': 3, 'lambda_l1': 3.5363275814902857, 'lambda_l2': 1.3452203042383943}. Best is trial 3 with value: 0.8775.
[I 2026-02-16 17:14:52,914] Trial 10 finished with value: 0.8735 and parameters: {'learning_rate': 0.11195947232174722, 'num_leaves': 296, 'max_depth': 7, 'min_data_in_leaf': 46, 'feature_fraction': 0.6034744172961057, 'bagging_fraction': 0.8767378266414092, 'bagging_freq': 4, 'lambda_l1': 4.730134236481043, 'lambda_l2': 4.218537415301099}. Best is trial 3 with value: 0.8775.
[I 2026-02-16 17:14:57,129] Trial 11 finished with value: 0.8735 and parameters: {'learning_rate': 0.044155074701982475, 'num_leaves': 24, 'max_depth': 12, 'min_data_in_leaf': 96, 'feature_fraction': 0.9943846445496305, 'bagging_fraction': 0.6145506260665438, 'bagging_freq': 5, 'lambda_l1': 4.111622922660484, 'lambda_l2': 1.8953064908224124}. Best is trial 3 with value: 0.8775.
[I 2026-02-16 17:14:58,849] Trial 12 finished with value: 0.872 and parameters: {'learning_rate': 0.05433068346085996, 'num_leaves': 28, 'max_depth': 12, 'min_data_in_leaf': 99, 'feature_fraction': 0.837855661949251, 'bagging_fraction': 0.6039609685110555, 'bagging_freq': 4, 'lambda_l1': 2.377030018877465, 'lambda_l2': 3.8143313926722286}. Best is trial 3 with value: 0.8775.
[I 2026-02-16 17:15:02,935] Trial 13 finished with value: 0.8745 and parameters: {'learning_rate': 0.010550738665855848, 'num_leaves': 76, 'max_depth': 8, 'min_data_in_leaf': 82, 'feature_fraction': 0.9996499484733484, 'bagging_fraction': 0.7323540087732562, 'bagging_freq': 3, 'lambda_l1': 2.440983663554678, 'lambda_l2': 1.5540544866935675}. Best is trial 3 with value: 0.8775.
[I 2026-02-16 17:15:04,787] Trial 14 finished with value: 0.8755 and parameters: {'learning_rate': 0.053869663338605336, 'num_leaves': 159, 'max_depth': 12, 'min_data_in_leaf': 55, 'feature_fraction': 0.7710958688559518, 'bagging_fraction': 0.7974531417821322, 'bagging_freq': 5, 'lambda_l1': 4.088544476827125, 'lambda_l2': 2.440295552871546}. Best is trial 3 with value: 0.8775.
[I 2026-02-16 17:15:05,830] Trial 15 finished with value: 0.8715 and parameters: {'learning_rate': 0.11300615328207925, 'num_leaves': 73, 'max_depth': 7, 'min_data_in_leaf': 70, 'feature_fraction': 0.6897161695316771, 'bagging_fraction': 0.6591245317457644, 'bagging_freq': 3, 'lambda_l1': 4.0401102174890795, 'lambda_l2': 3.524731345105235}. Best is trial 3 with value: 0.8775.
[I 2026-02-16 17:15:09,673] Trial 16 finished with value: 0.871 and parameters: {'learning_rate': 0.06481040676729928, 'num_leaves': 175, 'max_depth': 10, 'min_data_in_leaf': 89, 'feature_fraction': 0.6049435089560313, 'bagging_fraction': 0.802988446839727, 'bagging_freq': 5, 'lambda_l1': 3.139288470188945, 'lambda_l2': 2.3342734579813302}. Best is trial 3 with value: 0.8775.
[I 2026-02-16 17:15:12,655] Trial 17 finished with value: 0.873 and parameters: {'learning_rate': 0.03591100199925996, 'num_leaves': 131, 'max_depth': 11, 'min_data_in_leaf': 30, 'feature_fraction': 0.8660258397868077, 'bagging_fraction': 0.9987103570173139, 'bagging_freq': 2, 'lambda_l1': 1.9659270706423952, 'lambda_l2': 1.2283428763010487}. Best is trial 3 with value: 0.8775.
[I 2026-02-16 17:15:13,775] Trial 18 finished with value: 0.8765 and parameters: {'learning_rate': 0.11837134554032928, 'num_leaves': 275, 'max_depth': 8, 'min_data_in_leaf': 53, 'feature_fraction': 0.9554790492980406, 'bagging_fraction': 0.7589269596276216, 'bagging_freq': 7, 'lambda_l1': 3.7417920471100805, 'lambda_l2': 2.8490794630762153}. Best is trial 3 with value: 0.8775.
[I 2026-02-16 17:15:14,736] Trial 19 finished with value: 0.8705 and parameters: {'learning_rate': 0.12274969230061256, 'num_leaves': 282, 'max_depth': 8, 'min_data_in_leaf': 47, 'feature_fraction': 0.7840496675821792, 'bagging_fraction': 0.7590233830766914, 'bagging_freq': 7, 'lambda_l1': 4.471551481141064, 'lambda_l2': 3.9309850703458857}. Best is trial 3 with value: 0.8775.
[I 2026-02-16 17:15:15,874] Trial 20 finished with value: 0.878 and parameters: {'learning_rate': 0.12604441436118582, 'num_leaves': 271, 'max_depth': 6, 'min_data_in_leaf': 23, 'feature_fraction': 0.7224739583229978, 'bagging_fraction': 0.84022207207405, 'bagging_freq': 6, 'lambda_l1': 3.8848271764275366, 'lambda_l2': 4.859940132586908}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:17,054] Trial 21 finished with value: 0.874 and parameters: {'learning_rate': 0.12486388627434514, 'num_leaves': 260, 'max_depth': 6, 'min_data_in_leaf': 25, 'feature_fraction': 0.7310680366624924, 'bagging_fraction': 0.8449830955641298, 'bagging_freq': 6, 'lambda_l1': 3.6539330185596177, 'lambda_l2': 4.491454544326124}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:18,326] Trial 22 finished with value: 0.873 and parameters: {'learning_rate': 0.10284453738323449, 'num_leaves': 248, 'max_depth': 5, 'min_data_in_leaf': 20, 'feature_fraction': 0.6450435130940382, 'bagging_fraction': 0.9094547782011054, 'bagging_freq': 7, 'lambda_l1': 4.389324007866739, 'lambda_l2': 0.011079565826425775}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:19,370] Trial 23 finished with value: 0.8725 and parameters: {'learning_rate': 0.1294225753368995, 'num_leaves': 272, 'max_depth': 6, 'min_data_in_leaf': 53, 'feature_fraction': 0.7121369448964395, 'bagging_fraction': 0.8270137227058451, 'bagging_freq': 6, 'lambda_l1': 3.7857710890056797, 'lambda_l2': 3.260955565980862}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:22,605] Trial 24 finished with value: 0.876 and parameters: {'learning_rate': 0.11562590226375702, 'num_leaves': 192, 'max_depth': 9, 'min_data_in_leaf': 40, 'feature_fraction': 0.6447631893828004, 'bagging_fraction': 0.7693506065767846, 'bagging_freq': 7, 'lambda_l1': 2.74895442514348, 'lambda_l2': 4.876323959515173}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:23,749] Trial 25 finished with value: 0.8695 and parameters: {'learning_rate': 0.09716306784215589, 'num_leaves': 148, 'max_depth': 6, 'min_data_in_leaf': 60, 'feature_fraction': 0.8119326266775629, 'bagging_fraction': 0.9080245575386678, 'bagging_freq': 6, 'lambda_l1': 4.967593839682265, 'lambda_l2': 4.287136941362277}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:24,711] Trial 26 finished with value: 0.868 and parameters: {'learning_rate': 0.13551152112196296, 'num_leaves': 182, 'max_depth': 9, 'min_data_in_leaf': 71, 'feature_fraction': 0.7590117090155665, 'bagging_fraction': 0.9559554359010785, 'bagging_freq': 2, 'lambda_l1': 4.41818862672578, 'lambda_l2': 1.662827893080017}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:26,397] Trial 27 finished with value: 0.873 and parameters: {'learning_rate': 0.07169178672201688, 'num_leaves': 300, 'max_depth': 7, 'min_data_in_leaf': 19, 'feature_fraction': 0.687907164037577, 'bagging_fraction': 0.7406341623537004, 'bagging_freq': 7, 'lambda_l1': 3.8186786075745136, 'lambda_l2': 3.6965663904280577}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:27,848] Trial 28 finished with value: 0.8755 and parameters: {'learning_rate': 0.1049914446529736, 'num_leaves': 251, 'max_depth': 8, 'min_data_in_leaf': 48, 'feature_fraction': 0.6425608935840604, 'bagging_fraction': 0.9215325112284953, 'bagging_freq': 4, 'lambda_l1': 3.354119507863566, 'lambda_l2': 2.9408491689138976}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:28,708] Trial 29 finished with value: 0.871 and parameters: {'learning_rate': 0.14991542003497998, 'num_leaves': 283, 'max_depth': 5, 'min_data_in_leaf': 10, 'feature_fraction': 0.7308133296503501, 'bagging_fraction': 0.6768377315771904, 'bagging_freq': 6, 'lambda_l1': 2.8242032729798856, 'lambda_l2': 4.997215489688149}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:29,683] Trial 30 finished with value: 0.877 and parameters: {'learning_rate': 0.12019329078182522, 'num_leaves': 209, 'max_depth': 11, 'min_data_in_leaf': 56, 'feature_fraction': 0.9634540336241189, 'bagging_fraction': 0.7763610056983095, 'bagging_freq': 6, 'lambda_l1': 4.563159282775698, 'lambda_l2': 3.1990550662678388}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:30,784] Trial 31 finished with value: 0.8755 and parameters: {'learning_rate': 0.12125582082403506, 'num_leaves': 216, 'max_depth': 11, 'min_data_in_leaf': 55, 'feature_fraction': 0.945984128474124, 'bagging_fraction': 0.7790367826488721, 'bagging_freq': 6, 'lambda_l1': 4.540351871767366, 'lambda_l2': 3.2723468654425822}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:31,765] Trial 32 finished with value: 0.8695 and parameters: {'learning_rate': 0.13917098313762924, 'num_leaves': 201, 'max_depth': 10, 'min_data_in_leaf': 68, 'feature_fraction': 0.9785489722534324, 'bagging_fraction': 0.8280903928811543, 'bagging_freq': 5, 'lambda_l1': 4.0892128910623295, 'lambda_l2': 2.157047376484145}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:35,018] Trial 33 finished with value: 0.8745 and parameters: {'learning_rate': 0.08648568231897344, 'num_leaves': 240, 'max_depth': 11, 'min_data_in_leaf': 41, 'feature_fraction': 0.9188255810174625, 'bagging_fraction': 0.7151288879470159, 'bagging_freq': 7, 'lambda_l1': 4.786406740153124, 'lambda_l2': 2.7172310892762663}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:36,133] Trial 34 finished with value: 0.8745 and parameters: {'learning_rate': 0.10930207381452854, 'num_leaves': 267, 'max_depth': 9, 'min_data_in_leaf': 61, 'feature_fraction': 0.8813659691570339, 'bagging_fraction': 0.741027336641028, 'bagging_freq': 7, 'lambda_l1': 4.202414739067565, 'lambda_l2': 3.0656240055928086}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:37,052] Trial 35 finished with value: 0.8775 and parameters: {'learning_rate': 0.1302803372562868, 'num_leaves': 202, 'max_depth': 10, 'min_data_in_leaf': 33, 'feature_fraction': 0.9591943003451406, 'bagging_fraction': 0.6948390396276759, 'bagging_freq': 1, 'lambda_l1': 4.980301098697289, 'lambda_l2': 2.7863374294987997}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:38,003] Trial 36 finished with value: 0.872 and parameters: {'learning_rate': 0.1312839375173642, 'num_leaves': 202, 'max_depth': 10, 'min_data_in_leaf': 17, 'feature_fraction': 0.9729715300880272, 'bagging_fraction': 0.6485838103089578, 'bagging_freq': 1, 'lambda_l1': 4.9475105915871875, 'lambda_l2': 2.5092368361943027}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:38,829] Trial 37 finished with value: 0.873 and parameters: {'learning_rate': 0.14430653055710257, 'num_leaves': 164, 'max_depth': 11, 'min_data_in_leaf': 36, 'feature_fraction': 0.8558274350398348, 'bagging_fraction': 0.6922033748875998, 'bagging_freq': 1, 'lambda_l1': 4.634726135366475, 'lambda_l2': 1.8926344395707928}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:40,424] Trial 38 finished with value: 0.8705 and parameters: {'learning_rate': 0.09891234235867663, 'num_leaves': 122, 'max_depth': 10, 'min_data_in_leaf': 28, 'feature_fraction': 0.8092613227255172, 'bagging_fraction': 0.9745419274504115, 'bagging_freq': 2, 'lambda_l1': 0.7992866714499192, 'lambda_l2': 0.9361247891768358}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:41,348] Trial 39 finished with value: 0.872 and parameters: {'learning_rate': 0.12870869947782182, 'num_leaves': 215, 'max_depth': 12, 'min_data_in_leaf': 23, 'feature_fraction': 0.8985574942676331, 'bagging_fraction': 0.6423067878517774, 'bagging_freq': 1, 'lambda_l1': 4.310563047937883, 'lambda_l2': 3.5563844429006215}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:42,025] Trial 40 finished with value: 0.8695 and parameters: {'learning_rate': 0.14503476705127288, 'num_leaves': 95, 'max_depth': 3, 'min_data_in_leaf': 15, 'feature_fraction': 0.6768895868452648, 'bagging_fraction': 0.8835367388038171, 'bagging_freq': 2, 'lambda_l1': 4.6824782154999305, 'lambda_l2': 4.176379786466523}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:43,012] Trial 41 finished with value: 0.87 and parameters: {'learning_rate': 0.1184546974936842, 'num_leaves': 147, 'max_depth': 9, 'min_data_in_leaf': 44, 'feature_fraction': 0.9455490949868887, 'bagging_fraction': 0.7044500166254238, 'bagging_freq': 1, 'lambda_l1': 3.8377631932160488, 'lambda_l2': 2.725657882486752}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:43,982] Trial 42 finished with value: 0.876 and parameters: {'learning_rate': 0.1375374861222247, 'num_leaves': 224, 'max_depth': 11, 'min_data_in_leaf': 51, 'feature_fraction': 0.9662058724467131, 'bagging_fraction': 0.7906899047927443, 'bagging_freq': 6, 'lambda_l1': 3.3458303110308907, 'lambda_l2': 2.9505937897716743}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:46,610] Trial 43 finished with value: 0.8745 and parameters: {'learning_rate': 0.12590085931183573, 'num_leaves': 179, 'max_depth': 10, 'min_data_in_leaf': 32, 'feature_fraction': 0.9294526935258413, 'bagging_fraction': 0.8132617149917128, 'bagging_freq': 2, 'lambda_l1': 3.9180247954036256, 'lambda_l2': 2.100992562719769}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:48,087] Trial 44 finished with value: 0.872 and parameters: {'learning_rate': 0.09490754532537797, 'num_leaves': 237, 'max_depth': 7, 'min_data_in_leaf': 58, 'feature_fraction': 0.9071765514532306, 'bagging_fraction': 0.7541278715634102, 'bagging_freq': 3, 'lambda_l1': 4.9901757758105365, 'lambda_l2': 2.5926503784841923}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:49,166] Trial 45 finished with value: 0.876 and parameters: {'learning_rate': 0.11827873260090746, 'num_leaves': 279, 'max_depth': 8, 'min_data_in_leaf': 65, 'feature_fraction': 0.9357868522388929, 'bagging_fraction': 0.7277038807269993, 'bagging_freq': 5, 'lambda_l1': 3.4859291659788765, 'lambda_l2': 3.082782266646337}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:50,222] Trial 46 finished with value: 0.8755 and parameters: {'learning_rate': 0.10700583823644319, 'num_leaves': 259, 'max_depth': 6, 'min_data_in_leaf': 75, 'feature_fraction': 0.9877122321854667, 'bagging_fraction': 0.8628099620013658, 'bagging_freq': 1, 'lambda_l1': 4.267595949825732, 'lambda_l2': 2.311234544613581}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:51,609] Trial 47 finished with value: 0.874 and parameters: {'learning_rate': 0.07743367215899441, 'num_leaves': 192, 'max_depth': 11, 'min_data_in_leaf': 37, 'feature_fraction': 0.9620640718061468, 'bagging_fraction': 0.6785159249191093, 'bagging_freq': 6, 'lambda_l1': 3.6543590355942808, 'lambda_l2': 3.9521071420434124}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:52,406] Trial 48 finished with value: 0.8725 and parameters: {'learning_rate': 0.1414933811547778, 'num_leaves': 210, 'max_depth': 4, 'min_data_in_leaf': 44, 'feature_fraction': 0.625642218762656, 'bagging_fraction': 0.7813822174871389, 'bagging_freq': 4, 'lambda_l1': 3.045882019917915, 'lambda_l2': 3.4226445158522}. Best is trial 20 with value: 0.878.
[I 2026-02-16 17:15:53,453] Trial 49 finished with value: 0.878 and parameters: {'learning_rate': 0.13392973328977603, 'num_leaves': 165, 'max_depth': 12, 'min_data_in_leaf': 51, 'feature_fraction': 0.6996379302146226, 'bagging_fraction': 0.7591113371966715, 'bagging_freq': 7, 'lambda_l1': 0.21116843889083192, 'lambda_l2': 1.8802797042373123}. Best is trial 20 with value: 0.878.

(0.878,
 {'learning_rate': 0.12604441436118582,
  'num_leaves': 271,
  'max_depth': 6,
  'min_data_in_leaf': 23,
  'feature_fraction': 0.7224739583229978,
  'bagging_fraction': 0.84022207207405,
  'bagging_freq': 6,
  'lambda_l1': 3.8848271764275366,
  'lambda_l2': 4.859940132586908})

In [32]:
study.best_value
study.best_params

{'learning_rate': 0.12604441436118582,
 'num_leaves': 271,
 'max_depth': 6,
 'min_data_in_leaf': 23,
 'feature_fraction': 0.7224739583229978,
 'bagging_fraction': 0.84022207207405,
 'bagging_freq': 6,
 'lambda_l1': 3.8848271764275366,
 'lambda_l2': 4.859940132586908}

In [33]:
best_params = study.best_params
best_params.update({
    "objective": "multiclass",
    "num_class": y.nunique(),
    "metric": "multi_logloss",
    "verbosity": -1
})

final_model = lgb.train(
    best_params,
    lgb.Dataset(X_train, label=y_train),
    num_boost_round=500
)

In [34]:
study.best_value

0.878

In [35]:
from sklearn.metrics import accuracy_score

y_pred = final_model.predict(X_test)
y_pred = np.argmax(y_pred, axis=1)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy Score:", accuracy)

Accuracy Score: 0.8745

In [36]:
import joblib

joblib.dump(final_model, "fertilizer_model.pkl")
joblib.dump(target_encoder, "target_encoder.pkl")
joblib.dump(label_encoders, "feature_encoders.pkl")

['feature_encoders.pkl']

In [49]:
import numpy as np
import pandas as pd

def predict_fertilizer(new_data_dict):

    # Convert input dictionary to DataFrame
    new_df = pd.DataFrame([new_data_dict])

    # Apply same feature engineering
    new_df["NPK_Ratio"] = (
        new_df["Nitrogen_Level"] +
        new_df["Phosphorus_Level"] +
        new_df["Potassium_Level"]
    ) / 3

    new_df["Moisture_Rain_Interaction"] = (
        new_df["Soil_Moisture"] * new_df["Rainfall"]
    )

    new_df["Climate_Stress"] = (
        new_df["Temperature"] / (new_df["Humidity"] + 1)
    )

    for col in categorical_features:
       if new_df[col][0] in label_encoders[col].classes_:
          new_df[col] = label_encoders[col].transform(new_df[col])
       else:
          new_df[col] = 0  # fallback for unseen category

    #  Predict
    prediction = final_model.predict(new_df)
    prediction = np.argmax(prediction, axis=1)

    #  Convert back to fertilizer name
    fertilizer_name = target_encoder.inverse_transform(prediction)

    return fertilizer_name[0]

In [53]:
new_farmer_data = {
    "Soil_Type": "hehe",
    "Soil_pH": 6.5,
    "Soil_Moisture": 35,
    "Organic_Carbon": 0.8,
    "Electrical_Conductivity": 0.3,
    "Nitrogen_Level": 50,
    "Phosphorus_Level": 40,
    "Potassium_Level": 45,
    "Temperature": 28,
    "Humidity": 65,
    "Rainfall": 120,
    "Crop_Type": "Wheat",
    "Crop_Growth_Stage": "Vegetative",
    "Season": "Rabi",
    "Irrigation_Type": "Drip",
    "Previous_Crop": "Rice",
    "Region": "North"
}

In [54]:
predict_fertilizer(new_farmer_data)

'Urea'